### ISSUE TITLE
"We received a bad request" error logging in.

### ISSUE THREAD

**Issue by glennblock** [microsoftgraph/nodejs-webhooks-rest-sample#15]
Node version: 5.10.1. Also tested with 8.1.2.

I've created an application on my personal Microsoft account which I have configured the app to use. I am running locally and using ngrok. When I try to login with the same account I get the following error: "We received a bad request" with these details:

```
-- | -- | -- | -- | --
Additional technical information:
Correlation ID: 368bda08-7352-4706-842c-13075be3eca2
Timestamp: 2017-11-06 04:41:45Z
AADSTS50020: We are unable to issue tokens from this api version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.
```

**Comment by jamescro** [comment]
Thank you for bringing this to our attention. You were correct in [this issue](https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/issues/14) that the Readme instructions need updating, but the apps.dev.microsoft.com URL isn't the correct one. 

This sample uses the [ADAL for Node](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs) library, which requires clients that are registered on portal.azure.com. 

So you still need to go to [the old URL](https://ms.portal.azure.com/#blade/Microsoft_AAD_IAM/ApplicationsListBlade) and follow these [instructions for configuring it](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications). You'll need to use the "New application registration" wizard on that blade to configure a new Web application with the information listed in the Readme. We'll need to update the configuration steps, since that configuration tool to which this sample used to link no longer exists.

Also, that auth library (and webhooks more generally) work only with work or school accounts, so your personal (live.com, outlook.com) Microsoft account won't work with this sample. That prerequisite should be added to the readme.

I'm also working on your third issue. That one is proving to be more difficult to sort out. I will comment on that issue as I learn more.

**Comment by jamescro** [comment]
I've updated the app registration steps and prerequisites in the readme, so I'll close this issue for now. Please reopen if you discover additional problems with the app setup steps.

**Comment by glennblock** [comment]
Hi Jim, I will take a look, thanks!
