### ISSUE TITLE
Logging in with corp account returns [object Object]

### ISSUE THREAD

**Issue by glennblock** [microsoftgraph/nodejs-webhooks-rest-sample#16]
Running locally and logging into my corp account I get a weird page after accepting in the app permissions dialog. The app is redirected to the callback page. but shows the screen below.

![screen shot 2017-11-05 at 8 51 17 pm](https://user-images.githubusercontent.com/141124/32425884-619997ec-c26b-11e7-87e6-b6ebce269dbe.png)

**Comment by glennblock** [comment]
Adding some debug output to show the error I see the following

```
{ error:
   { code: 'ExtensionError',
     message: 'Operation: Create; Exception: [Status Code: NotFound; Reason: Not Found]',
     innerError:
      { 'request-id': '6674905d-8a56-466c-87ec-5d639a57afac',
        date: '2017-11-06T05:04:42' } } }
```

**Comment by jamescro** [comment]
I can reproduce this, but I haven't yet tracked down the problem. I believe that the "createSubscription" call in bin/www is failing, because I'm seeing these errors when the sample tries to run the "saveSubscription" call in auth.js: Error: SQLITE_ERROR: no such table: Subscription

Are you seeing that error?

I'll let you know as I learn more.

**Comment by Hongbo-Miao** [comment]
Weird. I just tested both on macOS and Windows. Tried different browsers, all work well. Need more time to figure out what causes the issue.

**Comment by Hongbo-Miao** [comment]
@glennblock I saw a situation before. It is because the organization disable even basic access.

Can you try to log in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and try these two?

![image](https://user-images.githubusercontent.com/3375461/32522769-7cb31374-c3cd-11e7-9bf7-f91c28e42251.png)

**Comment by jamescro** [comment]
I can make the page load correctly (without the [object Object] output) by commenting line 39 in auth.js: 
`saveSubscription(subscriptionData, null);`

This causes the sample to not work, though, because the code in listen.js depends on that subscription being saved.
I think that this does demonstrate that the SQL_Lite error is related to this problem. It looks like in some cases the Subscription table isn't getting created when the app starts up, and that causes the saveSubscription code to fail in a way that results in the broken page.

Hongbo, do you have any idea what might cause this startup error? There clearly is an environmental component if some people can reproduce and others can't.

**Comment by skaspi** [comment]
Have the same problem

**Comment by jamescro** [comment]
Thanks for the additional data point. We're still investigation. Since this error seems to have potentially more than one cause, and it's linked to environmental factors, it's hard to debug. Do you see the SQL_Lite error in your output? Do you see any other errors?

**Comment by skaspi** [comment]
Thanks for a prompt reply.

I'm running Power Shell and that is what I see:

![image](https://user-images.githubusercontent.com/27776921/32924635-422a4f1c-cb46-11e7-8224-d8055908044d.png)

**Comment by glennblock** [comment]
Sorry I haven’t had cycles on this, Work took over, but I will look into
what errors I am seeing.

**Comment by Hongbo-Miao** [comment]
@jamescro I really have no idea, I tested on both my Windows and macOS without issue. Let's meet tomorrow and try on your machine. If SQLite cause issue, we can remove that part. I want to simplify the demo to help people focus on how to use webhooks.

**Comment by jamescro** [comment]
It looks like the database isn't getting created for some people, probably because the calls are running asynchronously. The best approach at this point would probably be to remove the SQLite dependency, which means that the code will need some thorough refactoring. I'm going to put that task into our backlog.

**Comment by jamescro** [comment]
I was able just now to get past this error by following these steps:
1. Delete the empty database.sqlite3 file that was generated the first time I ran "npm start" This database should be 8k, but in my case it was 0, which meant that the database had been created but the table had not.
2. Rerun "npm start." This time I got a database file that contained the table (and was 8k).

So this problem occurs when the "createDatabase" function that runs on startup fails to create a table. I don't know why that function failed the first time around, but it worked for me after I deleted the empty database and tried again.

Could you try again and see if that fixes your problem? I can look some more to see why that function fails sometimes and works at others.

**Comment by skaspi** [comment]
Thank you very much, but the problem still exists.I have the database.sqlite3 of 8 KB size from the start.

**Comment by jamescro** [comment]
I haven't seen this problem occur when the database and the table both exist. I'll keep looking.

**Comment by stoconnor** [comment]
I also get the error below on a corp account. However, it's not related to the code, it's got to do with how your corp account is set up. I believe it's due to a Hosted Exchange on-prem, I have tried with another user where their mailbox is managed by office365 online and not on-prem - this works.

```
{ error:
   { code: 'ExtensionError',
     message: 'Operation: Create; Exception: [Status Code: NotFound; Reason: Not Found]',
     innerError:
      { 'request-id': '6674905d-8a56-466c-87ec-5d639a57afac',
        date: '2017-11-06T05:04:42' } } }
```

**Comment by stoconnor** [comment]
Also worth noting that [object Object] is ambiguous. Post the actual error message here and we might be able to guide you in the right direction.

For a quick route to get the specific error you can just change line 49 in auth.js to the following:
`            next(requestError.error.message);`

**Comment by jamescro** [comment]
Thanks @stoconnor. Since I can no longer reproduce that error, @skaspi could you try changing line 49 in auth.js to `next(requestError.error.message);` and report back with what error message you're seeing?

**Comment by jamescro** [comment]
We are going to rewrite this sample in a way that doesn't require a database. I'll put that in our backlog and track the work there. Please reopen if you have any more information to share about what you're seeing.
